const $=s=>document.querySelector(s);
const escDate=value=>{if(!value)return null;const d=new Date(value);return Number.isNaN(d.getTime())?null:d};
const dateLabel=value=>{const d=escDate(value);return d?new Intl.DateTimeFormat("it-IT",{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"UTC"}).format(d):""};
const nameOf=(obj,keys)=>{if(!obj||typeof obj!=="object")return"";const key=Object.keys(obj).find(k=>keys.includes(k.toLowerCase()));return key?obj[key]:""};
const cell=(tag,text,cls)=>{const el=document.createElement(tag);if(cls)el.className=cls;el.textContent=text;return el};

async function loadTranscripts(){
  const response=await fetch("/api/refresh",{cache:"no-store"});const payload=await response.json();if(!response.ok)throw Error(payload.error||`HTTP ${response.status}`);
  const files=payload.files||[],candidates=[],errors=[];
  for(const file of files){
    if(file.error){errors.push(file);continue}
    const data=file.data||{},candidate=data.candidate||{};
    const candidateName=candidate.name||file.name||"Candidato";
    const certs=Array.isArray(data.certs)?data.certs:[];
    candidates.push({name:candidateName,source:file.name,certs:certs.map(c=>({id:String(c.ccatId??c.id??""),name:c.name||c.certificationName||"Certificazione senza nome",date:c.activeDate||c.activationDate||c.dateEarned||"",dateObj:escDate(c.activeDate||c.activationDate||c.dateEarned)}))});
  }
  return{candidates,errors,saved:payload.saved||0};
}
function showErrors(errors){const list=$("#errors");if(!list)return;list.replaceChildren();for(const e of errors){const li=cell("li",`${e.name||"Sorgente"} (${e.url}) — ${e.message||"errore di download"}`);list.append(li)}}
function normalizeClassifications(data){const list=Array.isArray(data)?data:(data.certifications||[]),map=new Map();for(const item of list){if(item.ccatId??item.id)map.set(String(item.ccatId??item.id),item);map.set(`name:${String(item.name||"").toLocaleLowerCase("it")}`,item)}return map}

function renderDashboard(candidates,classifications){
  const holder=$("#dashboard");const classList=Array.isArray(classifications)?classifications:(classifications.certifications||[]);const byId=normalizeClassifications(classifications);
  const included=classList.filter(x=>x.focusProduct===true);const dashboardType=x=>x.vcap?"Technical":(x.type||"Da classificare");const dashboardSpec=x=>x.vcap?"VCAP":(x.type==="Sales"?"Sales":(x.specification||""));
  const visible=included.map(x=>({...x,dashboardType:dashboardType(x),dashboardSpec:dashboardSpec(x)})).filter(x=>x.dashboardSpec);
  const products=[...new Set(visible.map(x=>x.product||"Altro"))].sort((a,b)=>a.localeCompare(b,"it"));
  const dimensions=[...new Map(visible.map(x=>[`${x.dashboardType}|||${x.dashboardSpec}`,{type:x.dashboardType,specification:x.dashboardSpec}])).values()].sort((a,b)=>a.type.localeCompare(b.type,"it")||a.specification.localeCompare(b.specification,"it"));
  const totals=new Map();let excluded=0;
  for(const person of candidates)for(const cert of person.certs){const category=byId.get(cert.id)||byId.get(`name:${cert.name.toLocaleLowerCase("it")}`);if(!category||category.focusProduct!==true||!dashboardSpec(category)){excluded++;continue}const key=`${category.product||"Altro"}|||${dashboardType(category)}|||${dashboardSpec(category)}`;if(!totals.has(key))totals.set(key,{pp:[],ce:[],unknown:[]});const level=category.level==="Proven Professional"?"pp":category.level==="Certified Expert"?"ce":"unknown";totals.get(key)[level].push({person:person.name,cert:cert.name,date:dateLabel(cert.date)})}
  if(!products.length||!dimensions.length){holder.innerHTML='<div class="empty-state">Nessuna certificazione è abilitata per il Focus Product. Attivala dalla pagina Impostazioni.</div>';renderKnights(candidates);return}
  const wrap=document.createElement("div");wrap.className="table-wrap";const table=document.createElement("table");table.className="matrix";const thead=document.createElement("thead"),top=document.createElement("tr"),subhead=document.createElement("tr"),focusHead=cell("th","Focus Product");focusHead.rowSpan=2;top.append(focusHead);const typeGroups=[...new Set(dimensions.map(d=>d.type))];for(const type of typeGroups){const th=cell("th",type);th.colSpan=dimensions.filter(d=>d.type===type).length;top.append(th);for(const d of dimensions.filter(x=>x.type===type)){const spec=d.specification==="Pre-Sales"?"Pre-sales":d.specification;subhead.append(cell("th",spec))}}thead.append(top,subhead);table.append(thead);const tbody=document.createElement("tbody");
  for(const product of products){const tr=document.createElement("tr");tr.append(cell("th",product));for(const d of dimensions){const entries=totals.get(`${product}|||${d.type}|||${d.specification}`)||{pp:[],ce:[],unknown:[]},td=document.createElement("td");td.className="level-cell";td.append(levelMetric("Proven Professional",entries.pp));td.append(levelMetric("Certified Expert",entries.ce));if(entries.unknown.length)td.append(cell("div",`Livello da impostare: ${entries.unknown.length}`,"level-count"));if(d.specification==="VCAP"){const certNames=[...new Set([...entries.pp,...entries.ce,...entries.unknown].map(x=>x.cert))].sort((a,b)=>a.localeCompare(b,"it"));if(certNames.length){const list=cell("ul","","vcap-certifications");for(const name of certNames)list.append(cell("li",name));td.append(list)}}td.title=[...entries.pp,...entries.ce,...entries.unknown].map(x=>`${x.person}: ${x.cert}${x.date?` (${x.date})`:""}`).join("\n");tr.append(td)}tbody.append(tr)}table.append(tbody);wrap.append(table);holder.replaceChildren(wrap);
  const note=$("#classification-note");note.textContent=`${visible.length} classificazioni abilitate al Focus Product · ${excluded} certificazioni escluse dal riepilogo.`;renderKnights(candidates);
}

function levelMetric(label,entries){const row=document.createElement("div");row.className="level-count";const name=cell("span",""),first=label.split(" ")[0],second=label.split(" ").slice(1).join(" ");name.append(document.createTextNode(first),document.createElement("br"),document.createTextNode(second));row.append(name);row.append(cell("strong",String(entries.length)));return row}
function renderKnights(candidates){const holder=$("#knight-table");if(!holder)return;const groups=new Map();for(const person of candidates)for(const cert of person.certs){if(!/broadcom\s+knight/i.test(cert.name))continue;const match=cert.name.match(/Broadcom\s+Knight(.*)$/i);const product=(match?match[1]:cert.name).replace(/^\s*[-:–—]+\s*/,"").trim()||cert.name;if(!groups.has(product))groups.set(product,new Set());groups.get(product).add(person.name)}if(!groups.size){holder.innerHTML='<div class="empty-state">Nessuna certificazione Knight trovata.</div>';return}const wrap=document.createElement("div");wrap.className="table-wrap";const table=document.createElement("table");table.className="knight-table";const thead=document.createElement("thead"),hr=document.createElement("tr");hr.append(cell("th","Prodotto"),cell("th","Knight"));thead.append(hr);table.append(thead);const tbody=document.createElement("tbody");for(const [product,names]of [...groups].sort((a,b)=>a[0].localeCompare(b[0],"it"))){const tr=document.createElement("tr");tr.append(cell("td",product));const td=document.createElement("td"),count=cell("span",String(names.size),"knight-count");count.title=[...names].join("\n");td.append(count);tr.append(td);tbody.append(tr)}table.append(tbody);wrap.append(table);holder.replaceChildren(wrap)}

function renderCertTable(candidates,showOld,query){
  const holder=$("#cert-table"),candidateNames=[...new Set(candidates.map(c=>c.name))];const map=new Map();const cutoff=new Date();cutoff.setFullYear(cutoff.getFullYear()-2);
  for(const person of candidates)for(const cert of person.certs){if(!map.has(cert.id||cert.name))map.set(cert.id||cert.name,{name:cert.name,dates:new Map(),latest:null});const entry=map.get(cert.id||cert.name);entry.dates.set(person.name,cert);if(cert.dateObj&&(!entry.latest||cert.dateObj>entry.latest))entry.latest=cert.dateObj}
  let records=[...map.values()].filter(cert=>cert.name.toLocaleLowerCase("it").includes(query.toLocaleLowerCase("it"))&&(showOld||[...cert.dates.values()].some(x=>!x.dateObj||x.dateObj>=cutoff))).sort((a,b)=>a.name.localeCompare(b.name,"it"));
  if(!records.length){holder.innerHTML='<div class="empty-state">Nessuna certificazione corrisponde ai filtri.</div>';return}
  const wrap=document.createElement("div");wrap.className="table-wrap";const table=document.createElement("table");table.className="matrix";const thead=document.createElement("thead"),hr=document.createElement("tr");hr.append(cell("th","Certificazione"));for(const name of candidateNames)hr.append(cell("th",name));thead.append(hr);table.append(thead);const tbody=document.createElement("tbody");
  for(const cert of records){const tr=document.createElement("tr");tr.append(cell("th",cert.name));for(const name of candidateNames){const td=document.createElement("td"),award=cert.dates.get(name),isOld=award?.dateObj&&award.dateObj<cutoff;if(award&&(!isOld||showOld))td.append(cell("span",dateLabel(award.date)||"Data non disponibile","date"));else td.append(cell("span","—","empty"));tr.append(td)}tbody.append(tr)}table.append(tbody);wrap.append(table);holder.replaceChildren(wrap);
}

function addSourceRow(url="",name=""){
  const tr=document.createElement("tr");for(const [value,placeholder]of[[url,"https://host/percorso/file.json"],[name,"Nome candidato"]]){const td=document.createElement("td"),input=document.createElement("input");input.value=value;input.placeholder=placeholder;input.type="text";td.append(input);tr.append(td)}const action=document.createElement("td"),remove=document.createElement("button");remove.className="danger";remove.type="button";remove.textContent="Rimuovi";remove.addEventListener("click",()=>tr.remove());action.append(remove);tr.append(action);$("#source-rows").append(tr)
}
function sourceDraft(){return[...$("#source-rows").rows].map(r=>({url:r.cells[0].querySelector("input").value.trim(),name:r.cells[1].querySelector("input").value.trim()})).filter(x=>x.url||x.name)}
function addClassificationRow(item){
  const tr=document.createElement("tr");tr._classification=item;if(item.isNew)tr.classList.add("new-classification");
  const name=cell("td",item.name);tr.append(name);
  tr.append(booleanCell(item.focusProduct,"Focus Product"),booleanCell(item.vcap,"VCAP"));
  const options={type:["Sales","Technical"],specification:["Pre-Sales","Implementation","Support","Architecture"],level:["Proven Professional","Certified Expert"]};
  for(const field of ["type","specification","level"]){const td=document.createElement("td"),select=document.createElement("select"),empty=document.createElement("option");empty.value="";empty.textContent="— Seleziona —";select.append(empty);for(const value of options[field]){const option=document.createElement("option");option.value=value;option.textContent=value;select.append(option)}select.value=item[field]||"";td.append(select);tr.append(td)}
  $("#classification-rows").append(tr);
}
function booleanCell(value,labelText){const td=document.createElement("td"),label=document.createElement("label"),input=document.createElement("input"),text=document.createElement("span");label.className="boolean-button";input.type="checkbox";input.checked=Boolean(value);input.setAttribute("aria-label",labelText);text.textContent=input.checked?"Attivo":"No";input.addEventListener("change",()=>{text.textContent=input.checked?"Attivo":"No"});label.append(input,text);td.append(label);return td}
function renderClassifications(items){const rows=$("#classification-rows");rows.replaceChildren();for(const item of items)addClassificationRow(item)}
function classificationDraft(){return[...$("#classification-rows").rows].map(row=>{const item={...row._classification};item.focusProduct=row.cells[1].querySelector('input[type="checkbox"]').checked;item.vcap=row.cells[2].querySelector('input[type="checkbox"]').checked;for(const [index,field]of["type","specification","level"].entries())item[field]=row.cells[index+3].querySelector("select").value;return item})}
async function loadClassificationSettings(){const response=await fetch("/api/classifications",{cache:"no-store"}),data=await response.json();if(!response.ok)throw Error(data.error||`HTTP ${response.status}`);renderClassifications(data.certifications||[]);const added=(data.certifications||[]).filter(x=>x.isNew).length;$("#classification-status").textContent=`${(data.certifications||[]).length} certificazioni · ${added} da classificare`}
async function refreshAndLoadClassifications(){const response=await fetch("/api/refresh",{cache:"no-store"}),data=await response.json();if(!response.ok)throw Error(data.error||`HTTP ${response.status}`);showErrors((data.files||[]).filter(x=>x.error));await loadClassificationSettings()}
async function initSettings(){const response=await fetch("/api/config",{cache:"no-store"}),data=await response.json();if(!response.ok)throw Error(data.error||`HTTP ${response.status}`);for(const x of data.sources||[])addSourceRow(x.url,x.name);$("#config-status").textContent=`${(data.sources||[]).length} URL caricate da config.json`;await refreshAndLoadClassifications()}
async function saveSettings(){const button=$("#save-config");button.disabled=true;$("#config-status").textContent="Salvataggio…";try{const response=await fetch("/api/config",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sources:sourceDraft()})}),data=await response.json();if(!response.ok)throw Error(data.error||`HTTP ${response.status}`);$("#source-rows").replaceChildren();for(const x of data.sources)addSourceRow(x.url,x.name);$("#config-status").textContent=`Configurazione salvata · ${data.sources.length} URL`;await refreshAndLoadClassifications()}catch(e){$("#config-status").textContent=`Errore: ${e.message}`}finally{button.disabled=false}}
async function saveClassifications(){const button=$("#save-classifications");button.disabled=true;$("#classification-status").textContent="Salvataggio classificazioni…";try{const response=await fetch("/api/classifications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({certifications:classificationDraft()})}),data=await response.json();if(!response.ok)throw Error(data.error||`HTTP ${response.status}`);renderClassifications(data.certifications);const added=data.certifications.filter(x=>x.isNew).length;$("#classification-status").textContent=`Classificazioni salvate · ${added} ancora da completare`}catch(e){$("#classification-status").textContent=`Errore: ${e.message}`}finally{button.disabled=false}}

async function init(){
  const page=document.body.dataset.page;
  if(page==="settings"){
    $("#add-source").addEventListener("click",()=>addSourceRow());$("#save-config").addEventListener("click",saveSettings);$("#save-classifications").addEventListener("click",saveClassifications);
    try{await initSettings()}catch(e){$("#config-status").textContent=`Errore configurazione: ${e.message}`}return;
  }
  let data;
  const redraw=()=>{if(!data)return;if(page==="dashboard")renderDashboard(data.candidates,data.classifications);else renderCertTable(data.candidates,$("#show-old").checked,$("#cert-search").value)};
  if(page==="table"){$("#show-old").addEventListener("change",redraw);$("#cert-search").addEventListener("input",redraw)}
  const refresh=async()=>{const button=$("#reload");button.disabled=true;$("#status").textContent="Download dei transcript…";try{const [transcripts,classResponse]=await Promise.all([loadTranscripts(),page==="dashboard"?fetch("/api/classifications",{cache:"no-store"}):Promise.resolve(null)]);let classifications={certifications:[]};if(classResponse){classifications=await classResponse.json();if(!classResponse.ok)throw Error(classifications.error||`HTTP ${classResponse.status}`)}data={...transcripts,classifications};showErrors(transcripts.errors);redraw();$("#status").textContent=`${transcripts.saved} file JSON scaricati · ${transcripts.candidates.length} candidati`}catch(e){$("#status").textContent=`Errore: ${e.message}`}finally{button.disabled=false}};
  $("#reload").addEventListener("click",refresh);await refresh();
}
document.addEventListener("DOMContentLoaded",init);
